<a href="https://colab.research.google.com/github/Asmee27/24102C2003_R-PROGRAMMING/blob/main/Week_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Matrix Operations
### Renaming the row and column names

In [5]:
x = matrix( nrow=4, ncol=3, data=c(1:12) )
x
 rownames(x) = c("r1", "r2", "r3", "r4")
 x
 colnames(x) = c("c1", "c2", "c3")
 x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

###Assigning a specified number to all matrix elements:

In [7]:
x = matrix( nrow=4, ncol=2, data=2 )
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

###Construction of a diagonal matrix, here the identity matrix of a dimension 3:

In [8]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

###Transpose of a matrix X:   X

In [10]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T )
x

 xt = t(x)
 xt

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

###Row and column sums

In [11]:
 x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
 x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

###Row and column means

In [15]:
x
print("rowSums")
rowSums(x)
print("colSums")
colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] "rowSums"

[1]  6  8 10 12

[1] "colSums"

[1] 10 26

###Access to rows, columns or submatrices

In [20]:
x = matrix( nrow=5, ncol=3, byrow=T, data=1:15)
x
print("Access 3rd row")
x[3,]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

[1] "Access 3rd row"

[1] 7 8 9

###Addition of a matrix with a constant

In [22]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x
print("Add +5 to every row")
x+5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

###Subtraction of a matrix with a constant

In [23]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

###Multiplication of a matrix with a constant

In [24]:
 x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

###Division of a matrix with a constant

In [25]:
 x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
 x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

###Addition and subtraction of matrices

In [30]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)
print("Addition")
x + y
print("Subtraction")
x - y
print("Multiplication")
4*x
x + 4*x
4*x - x

[1] "Addition"

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

[1] "Subtraction"

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

[1] "Multiplication"

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

###Concatenating matrices
####--Concatenating matrices row wise: rbind(x, y)
####--Concatenating matrices column wise: cbind(x, y)

In [33]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)
x
y
print("Column wise")
cbind(x, y)
print("Row wise")
rbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

[1] "Column wise"

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

[1] "Row wise"

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

###Inverse of matrix
####--solve() finds the inverse of a positive definite matrix

In [34]:
y = matrix( nrow = 2, ncol = 2, byrow = T,
data = c(84,100,100,120))
y
solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

###Eigen values and eigen vectors of matrix
####--eigen() finds the eigen values and eigen vectors of a positive
definite matrix

In [36]:
y = matrix( nrow = 2, ncol = 2, byrow = T, data = c(84,100,100,120))
y
eigen(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

###Logical Operators and Comparisons

In [39]:
# Use of | and ||
x=8
 (x < 10) || (x < 2)
x=18
 (x < 10) || (x < 2)
x = c(8,18)
(x < 10) | (x < 2)

[1] TRUE

[1] FALSE

[1]  TRUE FALSE

In [44]:
# Use of & and &&
 x = 5
  (x < 10) && (x > 2)
x = 15
  (x < 10) && (x > 2)
x <- c(3, 12)
(x < 10) & (x > 2)# & Operates on all the element

  x = 1:6 # Generates x=1,2,3,4,5,6
  (x > 2) & (x < 5)
  x[(x > 2) & (x < 5)]# Finds which values are greater than 2 and smaller than 5

[1] TRUE

[1] FALSE

[1]  TRUE FALSE

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

###Logical  Operators and Comparisons

In [45]:
 x = TRUE
 y = FALSE
 x & y # x AND y
 x | y # x OR y
 !x # negation of x

[1] FALSE

[1] TRUE

[1] FALSE