In [ ]:
# ------------------------------------------------------------
# 1. print() FUNCTION
# ------------------------------------------------------------

print("The zero occurs at")
print(2*pi)
print("radians")


# Multiple print statements
print("The zero occurs at")
print(2*pi)
print("radians")


# ------------------------------------------------------------
# 2. cat() FUNCTION
# ------------------------------------------------------------

cat("The zero occurs at", 2*pi, "radians.", "\n")


# ------------------------------------------------------------
# 3. DATE WITH cat()
# ------------------------------------------------------------

d = date()
d

cat("Today's date is:", d, "\n")


# ------------------------------------------------------------
# 4. sep ARGUMENT IN cat()
# ------------------------------------------------------------

x = 1:10
x

cat(x, sep = " ++ ")

cat("\n")

cat(x, sep = " / ")

cat("\n")


# ------------------------------------------------------------
# 5. USING VARIABLES WITH cat()
# ------------------------------------------------------------

x = 7

cat("The square of", x, "is", x^2, "!\n")


# ------------------------------------------------------------
# 6. FORMAT NUMERIC OUTPUT
# ------------------------------------------------------------

cat(
  "The square root of",
  x,
  "is approximately",
  format(sqrt(x), digits = 3),
  "\n"
)


# ------------------------------------------------------------
# 7. PRINTING VECTORS USING cat()
# ------------------------------------------------------------

evenno = c(2, 4, 6, 8, 10)

evenno

cat(
  "The first few even numbers are:",
  evenno,
  "...\n"
)


# ------------------------------------------------------------
# 8. fill AND labels ARGUMENTS
# ------------------------------------------------------------

x = 1:10
x

cat(
  x,
  fill = 2,
  labels = paste("(", letters[1:10], "):")
)



# ============================================================
# LECTURE 37
# PASTE FUNCTION
# ============================================================


# ------------------------------------------------------------
# 9. BASIC paste()
# ------------------------------------------------------------

paste(1:12)


# Alternative
as.character(1:12)


# ------------------------------------------------------------
# 10. JOINING STRINGS
# ------------------------------------------------------------

paste(
  "Everybody",
  "loves",
  "R Programming."
)


# ------------------------------------------------------------
# 11. paste() WITH sep
# ------------------------------------------------------------

paste(
  "Everybody",
  "loves",
  "R Programming.",
  sep = "*"
)


paste(
  "Everybody",
  "loves",
  "R Programming.",
  sep = "==="
)


# ------------------------------------------------------------
# 12. paste() WITH VECTOR
# ------------------------------------------------------------

names = c(
  "Prof. Singh",
  "Mr. Venkat",
  "Dr. Jha"
)

names


paste(
  names,
  "is",
  "a good",
  "person."
)


# ------------------------------------------------------------
# 13. collapse ARGUMENT
# ------------------------------------------------------------

names = c(
  "Prof. Singh",
  "Mr. Venkat",
  "Dr. Jha"
)


paste(
  names,
  "is",
  "a good",
  "person.",
  collapse = ", and "
)


# ------------------------------------------------------------
# 14. sep EXAMPLE
# ------------------------------------------------------------

paste(
  1,
  " is first",
  2,
  " is second",
  3,
  " is third",
  sep = "#"
)


# Observe role of spaces inside strings

paste(
  1,
  " is first ",
  2,
  " is second ",
  3,
  " is third ",
  sep = "#"
)


# ------------------------------------------------------------
# 15. CREATE VECTOR OF STRINGS
# ------------------------------------------------------------

x = paste(
  "Ex",
  1:5,
  sep = "_"
)

x


# Access individual elements

x[1]

x[2]

x[3]

x[5]


# ------------------------------------------------------------
# 16. paste() WITH collapse
# ------------------------------------------------------------

x = paste(
  "Ex",
  1:5,
  sep = "_",
  collapse = ""
)

x

x[1]


# ------------------------------------------------------------
# 17. DIFFERENCE BETWEEN VECTOR AND SINGLE STRING
# ------------------------------------------------------------

x = paste(
  "Ex",
  1:5,
  sep = "_"
)

x


x = paste(
  "Ex",
  1:5,
  sep = "_",
  collapse = ""
)

x


# ------------------------------------------------------------
# 18. paste0()
# ------------------------------------------------------------

paste0(1:10)


paste(1:10)


# ------------------------------------------------------------
# 19. paste0() VS paste()
# ------------------------------------------------------------

paste0(
  1:10,
  c(
    "st",
    "nd",
    "rd",
    rep("th", 7)
  )
)


paste(
  1:10,
  c(
    "st",
    "nd",
    "rd",
    rep("th", 7)
  )
)



# ============================================================
# LECTURE 38
# STRING SPLITTING
# strsplit()
# ============================================================


# ------------------------------------------------------------
# 20. BASIC strsplit()
# ------------------------------------------------------------

x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

x


strsplit(
  x,
  split = "!"
)


# ------------------------------------------------------------
# 21. SPLIT USING &!
# ------------------------------------------------------------

x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

x


strsplit(
  x,
  split = "&!"
)


# ------------------------------------------------------------
# 22. SPLIT USING !&
# ------------------------------------------------------------

x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

x


y = strsplit(
  x,
  split = "!&"
)

y


# ------------------------------------------------------------
# 23. ACCESS ELEMENTS OF strsplit RESULT
# ------------------------------------------------------------

y[[1]][1]

y[[1]][2]

y[[1]][3]


# ------------------------------------------------------------
# 24. SPLITTING DATES
# ------------------------------------------------------------

dates = c(
  "2020-07-24",
  "2021-08-25",
  "2022-09-26",
  "2023-10-27"
)

dates


datesplt = strsplit(
  dates,
  "-"
)

datesplt


# ------------------------------------------------------------
# 25. CONVERT SPLIT DATES INTO CHARACTER MATRIX
# ------------------------------------------------------------

datemat = matrix(
  unlist(datesplt),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datemat


# ------------------------------------------------------------
# 26. CONVERT SPLIT DATES INTO NUMERIC MATRIX
# ------------------------------------------------------------

datematrix = matrix(
  as.numeric(unlist(datesplt)),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datematrix


# ------------------------------------------------------------
# 27. SPLIT STRING INTO INDIVIDUAL CHARACTERS
# ------------------------------------------------------------

strsplit(
  "Shalabh",
  split = ""
)



# ============================================================
# LECTURE 39
# MANIPULATIONS WITH STRINGS AND ALPHABETS
# ============================================================


# ------------------------------------------------------------
# 28. nchar()
# COUNT NUMBER OF CHARACTERS
# ------------------------------------------------------------

x = "R course 24.07.2022"

y = "Number of participants: 25"


x
y


nchar(x)

nchar(y)


# ------------------------------------------------------------
# 29. nzchar()
# CHECK WHETHER STRING IS NON-EMPTY
# ------------------------------------------------------------

nzchar(x)

nzchar(y)


# ------------------------------------------------------------
# 30. nzchar() WITH VECTOR
# ------------------------------------------------------------

x = c(
  "Apple",
  "Banana",
  "Cake"
)

x

nzchar(x)


# Vector containing empty string

y = c(
  "Apple",
  "",
  "Cake"
)

y

nzchar(y)


# ------------------------------------------------------------
# 31. nchar() WITH CHARACTER VECTOR
# ------------------------------------------------------------

x = c(
  "Apple",
  "Banana",
  "Cake"
)

nchar(x)


# ------------------------------------------------------------
# 32. nchar() WITH NUMBERS
# ------------------------------------------------------------

y = c(2, 4, 6)

nchar(y)


z = c(
  11,
  222,
  3333
)

nchar(z)


z1 = c(
  1.1,
  2.22,
  3.333
)

nchar(z1)


# ============================================================
# LOWERCASE AND UPPERCASE
# ============================================================


# ------------------------------------------------------------
# 33. toupper()
# ------------------------------------------------------------

x = "R course will start from 24.07.2022"

x

toupper(x)


# ------------------------------------------------------------
# 34. tolower()
# ------------------------------------------------------------

z = "INDIAN INSTITUTE OF TECHNOLOGY"

z

tolower(z)


# ============================================================
# END OF WEEK 9
# ============================================================

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"
[1] "The zero occurs at"
[1] 6.283185
[1] "radians"
The zero occurs at 6.283185 radians.

[1] "Mon Sep 21 08:47:14 2026"

Today's date is: Mon Sep 21 08:47:14 2026

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10
The square of 7 is 49 !
The square root of 7 is approximately 2.65

[1]  2  4  6  8 10

The first few even numbers are: 2 4 6 8 10 ...

 [1]  1  2  3  4  5  6  7  8  9 10

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

[1] "Everybody loves R Programming."

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

[1] "1# is first#2# is second#3# is third"

[1] "1# is first #2# is second #3# is third "

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

[1] "The&!syntax&!of&!paste&!is"

[1] "available! &inthe online-help"

[1] NA

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

[1] "R course 24.07.2022"

[1] "Number of participants: 25"

[1] 19

[1] 26

[1] TRUE

[1] TRUE

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

[1] 5 6 4

[1] 1 1 1

[1] 2 3 4

[1] 3 4 5

[1] "R course will start from 24.07.2022"

[1] "R COURSE WILL START FROM 24.07.2022"

[1] "INDIAN INSTITUTE OF TECHNOLOGY"

[1] "indian institute of technology"